# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ashou\OneDrive\Documents\ImagePro\TASK_3\interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        self.ShearEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.ShearEdit.setObjectName("ShearEdit")
        self.gridLayout.addWidget(self.ShearEdit, 0, 5, 1, 1)
        self.ShearButton = QtWidgets.QPushButton(self.centralwidget)
        self.ShearButton.setObjectName("ShearButton")
        self.gridLayout.addWidget(self.ShearButton, 0, 6, 1, 1)
        self.RotateEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.RotateEdit.setMaximumSize(QtCore.QSize(140, 16777215))
        self.RotateEdit.setObjectName("RotateEdit")
        self.gridLayout.addWidget(self.RotateEdit, 0, 1, 1, 1)
        self.ConstructButton = QtWidgets.QPushButton(self.centralwidget)
        self.ConstructButton.setObjectName("ConstructButton")
        self.gridLayout.addWidget(self.ConstructButton, 0, 0, 1, 1)
        self.RotateButton = QtWidgets.QPushButton(self.centralwidget)
        self.RotateButton.setObjectName("RotateButton")
        self.gridLayout.addWidget(self.RotateButton, 0, 3, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Clockwise"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Anti-Clockwise"))
        self.ShearEdit.setText(_translate("MainWindow", "90"))
        self.ShearButton.setText(_translate("MainWindow", "Shear"))
        self.RotateEdit.setText(_translate("MainWindow", "90"))
        self.ConstructButton.setText(_translate("MainWindow", "Construct T"))
        self.RotateButton.setText(_translate("MainWindow", "Rotate"))
